run_name: WikiMEL
seed: 43
pretrained_model: 'openai/clip-vit-base-patch32'
lr: 1e-5


data:
  num_entity: 109976
  kb_img_folder: /yourpath/WikiMEL/kb_image
  mention_img_folder: /yourpath/WikiMEL/mention_image
  qid2id: /yourpath/WikiMEL/qid2id.json
  entity: /yourpath/WikiMEL/kb_entity_desc.json
  train_file: /yourpath/WikiMEL/WIKIMEL_train.json
  dev_file: /yourpath/WikiMEL/WIKIMEL_dev.json
  test_file: /yourpath/WikiMEL/WIKIMEL_test.json

  batch_file_folder: /yourpath/batch_data
  soft_labels_folder: /yourpath/soft_labels

  batch_size: 128
  num_workers: 8
  text_max_length: 40

  eval_chunk_size: 6000
  eval_batch_size: 20
  embed_update_batch_size: 512


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 96
  dv: 96
  dt: 512
  TGLU_hidden_dim: 96
  IDLU_hidden_dim: 96
  CMFU_hidden_dim: 96


trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 40
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 2
  log_every_n_steps: 30